version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    working_directory: /go/src/github.com/segmentio/ecs-station-agent
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            docker build -t segment/ecs-station-agent .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push segment/ecs-station-agent:latest
